#!/usr/bin/env python3
"""
scaffold_nextjs_tina.py — Emit the full Next.js (App Router) + self-hosted TinaCMS app
SKELETON in one command, so the agent spends effort on porting + content modeling, not
hand-writing ~20 config files. Reads assets/templates/, substitutes <name>, selects the
right per-deploy / per-db files, and writes a tree that builds clean before any porting.

  <out>/
    package.json  next.config.mjs  tsconfig.json  postcss.config.mjs  .env  .env.example  .gitignore  README.md
    tina/ config.tsx  database.ts  .gitignore  collections/{page,settings}.ts
    pages/api/tina/[...routes].ts
    app/ layout.tsx  page.tsx  home-view.tsx  globals.css
    components/blocks.tsx
    content/ pages/home.json  settings/index.json  users/index.json
    public/uploads/.gitkeep
    wrangler.jsonc  open-next.config.ts            (--deploy cloudflare only)

Dependency-free (stdlib only); idempotent (skips existing files unless --force).

Usage:
    python3 scaffold_nextjs_tina.py --out <dir> --name <slug> \
        [--analysis analysis.json] --deploy cloudflare|vercel [--db upstash|mongodb] \
        [--media git|r2|s3] [--templates DIR] [--force]
"""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_TEMPLATES = SCRIPT_DIR.parent / "assets" / "templates"

GITIGNORE = """\
# deps
/node_modules
# next
/.next/
/out/
# cloudflare / opennext
/.open-next/
.dev.vars
.wrangler/
# tina build artifact (regenerated by `tinacms build`)
/public/admin
# env
.env
.env*.local
# misc
.DS_Store
*.log
next-env.d.ts
"""

TINA_GITIGNORE = "__generated__\n"

ENV_LOCAL = "TINA_PUBLIC_IS_LOCAL=true\n"


def readme(name: str, deploy: str, db: str) -> str:
    deploy_block = (
        "## Deploy (Cloudflare)\n\n"
        "```bash\nnpm run deploy   # opennextjs-cloudflare build && … deploy\n```\n\n"
        "Set the production env vars in the Cloudflare dashboard (see `.env.example`) and "
        "`TINA_PUBLIC_IS_LOCAL=false`. Datalayer: Upstash Redis (HTTP — the store that runs on Workers).\n"
        if deploy == "cloudflare"
        else
        "## Deploy (Vercel)\n\n"
        "Push to GitHub, import in Vercel, add the env vars from `.env.example`. Provision "
        "**Upstash for Redis** via the Vercel Marketplace (Vercel KV was discontinued) — it injects "
        "`KV_REST_API_URL`/`KV_REST_API_TOKEN`."
        + ("  This app is configured for **MongoDB Atlas** — set `MONGODB_URI` instead.\n" if db == "mongodb" else "\n")
    )
    return f"""# {name}

A Next.js (App Router) + self-hosted **TinaCMS** app generated by `react-to-nextjs-cms`.
Content lives as JSON in `content/` and is committed to Git on save — no formal CMS.

## Local dev

```bash
npm install
npm run dev        # tinacms dev -c "next dev"  (local DB + local auth, no creds needed)
```

Open http://localhost:3000 — click a heading in edit mode to edit it in place.
The admin dashboard is at http://localhost:3000/admin.

## Content

- `content/pages/*.json` — one file per page (a list of section blocks).
- `content/settings/index.json` — site-wide nav / footer / contact.
- `content/users/index.json` — the admin login seed (change the password on first login).

Edit the schema in `tina/collections/*.ts`; wire on-page editing with `useTina` + `tinaField`
(`app/home-view.tsx`, `components/blocks.tsx`).

{deploy_block}
> Self-hosted Tina caveats: no search, build-time branch only, media is git/static (or wire S3/R2).
"""


def sub(text: str, name: str) -> str:
    return text.replace("<name>", name)


def load(tdir: Path, fname: str) -> str:
    p = tdir / fname
    if not p.exists():
        raise SystemExit(f"ERROR: template not found: {p}")
    return p.read_text(encoding="utf-8")


def write(path: Path, content: str, force: bool):
    if path.exists() and not force:
        print(f"  skip (exists): {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote: {path}")


def package_json(tdir: Path, deploy: str, db: str, name: str) -> str:
    pkg = json.loads(sub(load(tdir, f"package.{deploy}.json"), name))
    # strip comment-* helper keys
    pkg = {k: v for k, v in pkg.items() if not k.startswith("comment-")}
    if db == "mongodb":
        deps = pkg.get("dependencies", {})
        deps.pop("upstash-redis-level", None)
        deps["mongodb-level"] = "^0.0.4"
        pkg["dependencies"] = deps
    return json.dumps(pkg, indent=2) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold a Next.js + self-hosted TinaCMS app.")
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", required=True, help="App slug, e.g. protec")
    ap.add_argument("--analysis", default=None, help="analysis.json (informational)")
    ap.add_argument("--deploy", required=True, choices=["cloudflare", "vercel"])
    ap.add_argument("--db", default=None, choices=["upstash", "mongodb"])
    ap.add_argument("--media", default=None, choices=["git", "r2", "s3"])
    ap.add_argument("--templates", default=str(DEFAULT_TEMPLATES))
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    name = re.sub(r"[^a-z0-9-]", "-", args.name.lower()).strip("-") or "app"
    db = args.db or "upstash"  # default upstash: works on both platforms
    out = Path(args.out).expanduser()
    tdir = Path(args.templates).expanduser()

    if args.deploy == "cloudflare" and db == "mongodb":
        print("  WARNING: --deploy cloudflare --db mongodb — MongoDB's raw TCP is fragile on "
              "Workers (no SRV DNS, connection churn). Prefer --db upstash on Cloudflare. "
              "Proceeding as requested.")

    print(f"Scaffolding {name} -> {out}  (deploy={args.deploy}, db={db})")

    # ---- root config ----
    write(out / "package.json", package_json(tdir, args.deploy, db, name), args.force)
    write(out / "next.config.mjs", sub(load(tdir, f"next.config.{args.deploy}.mjs"), name), args.force)
    write(out / "tsconfig.json", load(tdir, "tsconfig.json"), args.force)
    write(out / "postcss.config.mjs", load(tdir, "postcss.config.mjs"), args.force)
    write(out / ".env", ENV_LOCAL, args.force)
    write(out / ".env.example", load(tdir, f"env.{args.deploy}.example"), args.force)
    write(out / ".gitignore", GITIGNORE, args.force)
    write(out / "README.md", readme(name, args.deploy, db), args.force)

    # ---- tina ----
    write(out / "tina/config.tsx", load(tdir, "tina-config.tsx"), args.force)
    write(out / "tina/database.ts", load(tdir, f"database.{db}.ts"), args.force)
    write(out / "tina/.gitignore", TINA_GITIGNORE, args.force)
    write(out / "tina/collections/page.ts", load(tdir, "collections-page.ts"), args.force)
    write(out / "tina/collections/settings.ts", load(tdir, "collections-settings.ts"), args.force)

    # ---- backend route (Pages Router file; coexists with app/) ----
    write(out / "pages/api/tina/[...routes].ts", load(tdir, "tina-backend-route.ts"), args.force)

    # ---- app ----
    write(out / "app/layout.tsx", sub(load(tdir, "app-layout.tsx"), name), args.force)
    write(out / "app/page.tsx", load(tdir, "app-page.tsx"), args.force)
    write(out / "app/home-view.tsx", load(tdir, "app-home-view.tsx"), args.force)
    write(out / "app/globals.css", load(tdir, "globals.css"), args.force)
    write(out / "components/blocks.tsx", load(tdir, "blocks.tsx"), args.force)

    # ---- content ----
    write(out / "content/pages/home.json", load(tdir, "content-home.json"), args.force)
    write(out / "content/settings/index.json", sub(load(tdir, "content-settings.json"), name), args.force)
    write(out / "content/users/index.json", load(tdir, "users-index.json"), args.force)
    write(out / "public/uploads/.gitkeep", "", args.force)

    # ---- cloudflare-only ----
    if args.deploy == "cloudflare":
        write(out / "wrangler.jsonc", sub(load(tdir, "wrangler.jsonc"), name), args.force)
        write(out / "open-next.config.ts", load(tdir, "open-next.config.ts"), args.force)

    print("\nSkeleton written. Next:")
    print(f"  cd {out} && npm install")
    print("  npm run dev          # tinacms dev -c \"next dev\"  → http://localhost:3000 (+ /admin)")
    print("  # then: Phase 4 tokens, Phase 5 port components/pages, Phase 6 externalize content")
    if args.deploy == "cloudflare":
        print("  npm run deploy       # opennextjs-cloudflare build && … deploy")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
